locals {
  name                                           = "${var.env}-${var.project_name}"
  s3_bucket_transcribe_input_name                = "${local.name}-s3-transcribe-input"
  s3_put_event_name                              = "${local.name}-s3-put-event"
  sfn_state_machine_name                         = "${local.name}-state-machine"
  sfn_role_name                                  = "${local.name}-sfn-role"
  s3_put_event_role_name                         = "${local.name}-s3-put-event-role"
  s3_put_event_policy_name                       = "${local.name}-s3-put-event-policy"
  ecr_repository_name                            = local.name
  lambda_function_s3_daily_dir_name              = "${local.name}-s3-daily-dir"
  lambda_function_s3_daily_dir_role_name         = "${local.name}-lambda-s3-daily-dir-role"
  lambda_function_s3_daily_dir_policy_name       = "${local.name}-lambda-s3-daily-dir-policy"
  scheduler_s3_daily_dir_name                    = "${local.name}-s3-daily-dir-scheduler"
  scheduler_s3_daily_dir_role_name               = "${local.name}-s3-daily-dir-scheduler-role"
  scheduler_s3_daily_dir_policy_name             = "${local.name}-s3-daily-dir-scheduler-policy"
  transcription_job_name                         = "${local.name}-transcription-job"
  sfn_policy_name                                = "${local.name}-sfn-policy"
  lambda_function_gen_nano_timestamp_name        = "${local.name}-gen-nano-timestamp"
  lambda_function_gen_nano_timestamp_role_name   = "${local.name}-lambda-gen-nano-timestamp-role"
  lambda_function_gen_nano_timestamp_policy_name = "${local.name}-lambda-gen-nano-timestamp-policy"
}